spring.application.name=dsa-question-picker

server.port=${PORT:8081}

spring.config.import=optional:file:/app/env.properties

spring.data.mongodb.uri=${MONGODB_URL}

frontend.url=${FRONTEND_URL}

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.redirect-uri=${BACKEND_URL}/auth/google/callback
spring.security.oauth2.client.registration.google.scope=profile,email

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.redirect-uri=${BACKEND_URL}/auth/github/callback
spring.security.oauth2.client.registration.github.scope=read:user,user:email

jwt.secret=${JWT_SECRET}
jwt.expiration.ms=604800000

eureka.client.service-url.defaultZone=${EUREKA_URL}/eureka

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

resilience4j.ratelimiter.instances.autofillRateLimiter.limitForPeriod=2
resilience4j.ratelimiter.instances.autofillRateLimiter.limitRefreshPeriod=10s
resilience4j.ratelimiter.instances.autofillRateLimiter.timeoutDuration=1s

resilience4j.bulkhead.instances.autofillBulkhead.maxConcurrentCalls=2
resilience4j.bulkhead.instances.autofillBulkhead.maxWaitDuration=0

spring.kafka.bootstrap-servers=${KAFKA_URL}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.admin.auto-create=true