spring.config.import=optional:file:/app/env.properties
spring.application.name=autofill-service

server.port=8082

eureka.client.service-url.defaultZone=${EUREKA_URL}/eureka

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true